replicaCount: 1

db:
  replicaCount: 1

image:
  repository: digdigdigdig/devops-project1
  tag: a6f6ad2d9fd6cc59acd87fc12170e5dc9491b498
  pullPolicy: IfNotPresent

service: 
  port: 9000

ingress:
  enabled: true
  host: "localhost"

metrics:
  enabled: true

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

ui:
  clockColor: "#222"
  background: "#ff0000"