replicaCount: 1

image:
  repository: digdigdigdig/devops-project1
  tag: 677ebb73340b9be9248e567e5addc28983f9a681
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30888

ingress:
  enabled: true
  host: "localhost"

metrics:
  enabled: true

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

ui:
  clockColor: "#a020f0"
  background: "#222"