pipeline {
    agent any
    stages {
        stage('1. Build Java App') {
            steps {
                dir('DevOps-Project-01/Java-Login-App') {
                    sh '''
                    pwd
                    ls -la
                    chmod +x mvnw
                    ./mvnw clean package -DskipTests
                    '''
                }
            }
        }
        stage('2. Docker Build') {
            steps {
                dir('DevOps-Project-01/Java-Login-App') {
                    sh '''
                    pwd
                    ls -la
                    /usr/local/bin/docker build -t digdigdigdig/java-login-app:test .
                    '''
                }
            }
        }
        stage('3. Deploy K8s') {
            steps {
                dir('DevOps-Project-01/Java-Login-App') {
                    sh '''
                    pwd
                    ls -la
                    kubectl apply -f k8s-deployment.yaml --dry-run=client
                    '''
                }
            }
        }
    }
}
