pipeline {
    agent any
    stages {
        stage('1. Maven Build') {
            steps {
                dir('DevOps-Project-01/Java-Login-App') {
                    sh '''
                    pwd
                    ls -la
                    # Use FULL PATH to Maven (Homebrew Apple Silicon)
                    /opt/homebrew/bin/mvn clean package -DskipTests
                    ls -la target/
                    '''
                }
            }
        }
        stage('2. Docker Build') {
            steps {
                dir('DevOps-Project-01/Java-Login-App') {
                    sh '''
                    pwd
                    # Find Docker path
                    ls /usr/local/bin/docker* /opt/homebrew/bin/docker* 2>/dev/null || echo "Docker paths"
                    /usr/local/bin/docker build -t digdigdigdig/java-login-app:test . || /opt/homebrew/bin/docker build -t digdigdigdig/java-login-app:test .
                    '''
                }
            }
        }
    }
}
