apiVersion: v1
kind: ConfigMap
metadata:
  name: project1-config
data:
  style.css: |
    body { 
      background: {{ .Values.ui.background }}; 
      color: {{ .Values.ui.clockColor }}; 
      display: flex; 
      justify-content: center; 
      align-items: center; 
      height: 100vh; 
      font-family: monospace; 
    }
    .clock { 
      text-align: center; 
      border: 2px solid {{ .Values.ui.clockColor }}; 
      padding: 20px; 
      border-radius: 10px; 
    }

  nginx.conf: |                          # ← only addition
    server {
      listen {{ .Values.service.port }};

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      location /stub_status {
        stub_status;
        allow 127.0.0.1;   # sidecar only
        deny all;
      }
    }