apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
data:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}