apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque  
data:
  db-port: {{ .Values.db.port | quote | b64enc }}
  db-user: {{ .Values.db.user | quote | b64enc }}
  db-password: {{ .Values.db.password | quote | b64enc }} 