pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t hello-world-django-app:${BUILD_NUMBER} .'
                sh 'docker images | grep hello-world-django-app'
            }
        }
        stage('Health Check') {
            steps {
                sh 'docker run --rm hello-world-django-app:${BUILD_NUMBER} python manage.py check --deploy'
            }
        }
        stage('Deploy') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', 
                                                 usernameVariable: 'DOCKER_USER', 
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker tag hello-world-django-app:${BUILD_NUMBER} $DOCKER_USER/hello-world-django-app:${BUILD_NUMBER}'
                    sh 'docker tag hello-world-django-app:${BUILD_NUMBER} $DOCKER_USER/hello-world-django-app:latest'
                    sh 'docker push $DOCKER_USER/hello-world-django-app:${BUILD_NUMBER}'
                    sh 'docker push $DOCKER_USER/hello-world-django-app:latest'
                }
            }
        }
    }
}
